#!/usr/bin/env bash

version=`ruby -r ./lib/parky/version.rb -e 'puts Parky::VERSION'`
dest=$1
ssh="ssh root@$dest"

rake build
scp pkg/parky-$version.gem root@$dest:
$ssh "sudo systemctl stop parky"
$ssh "sudo gem list | grep parky && gem uninstall parky"
$ssh "sudo gem install --no-ri --no-rdoc ./parky-$version.gem"
$ssh "sudo systemctl start parky"
$ssh "rm -f ./parky-$version.gem"
